/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BloodBankSummary {
  'totalPatients' : bigint,
  'inventory' : Array<[BloodGroup, bigint]>,
  'pendingRequests' : bigint,
  'totalDonors' : bigint,
}
export type BloodGroup = { 'abNeg' : null } |
  { 'abPos' : null } |
  { 'aNeg' : null } |
  { 'aPos' : null } |
  { 'bNeg' : null } |
  { 'bPos' : null } |
  { 'oNeg' : null } |
  { 'oPos' : null };
export interface BloodRequest {
  'status' : string,
  'requestedTimestamp' : Time,
  'patientId' : bigint,
  'unitsNeeded' : bigint,
  'bloodGroup' : BloodGroup,
  'notes' : string,
  'handledBy' : string,
}
export interface Donation {
  'testStatus' : string,
  'volumeMl' : bigint,
  'donorId' : bigint,
  'testedBy' : string,
  'collectionTimestamp' : Time,
  'notes' : string,
}
export interface Donor {
  'age' : bigint,
  'name' : string,
  'isActive' : boolean,
  'email' : string,
  'bloodGroup' : BloodGroup,
  'address' : string,
  'gender' : string,
  'registrationTimestamp' : Time,
  'lastDonationTimestamp' : Time,
  'phone' : string,
}
export interface InventoryUnit {
  'status' : string,
  'expiryTimestamp' : Time,
  'collectionId' : bigint,
  'collectedTimestamp' : Time,
  'bloodGroup' : BloodGroup,
  'units' : bigint,
}
export interface Patient {
  'age' : bigint,
  'hospital' : string,
  'urgency' : string,
  'name' : string,
  'isActive' : boolean,
  'bloodGroup' : BloodGroup,
  'gender' : string,
  'phone' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBloodRequest' : ActorMethod<[BloodRequest, bigint], bigint>,
  'createCollection' : ActorMethod<[Donation, bigint], bigint>,
  'createDonor' : ActorMethod<[Donor, bigint], bigint>,
  'createInventoryUnit' : ActorMethod<[InventoryUnit, bigint], bigint>,
  'createPatient' : ActorMethod<[Patient, bigint], bigint>,
  'deleteBloodRequest' : ActorMethod<[bigint], boolean>,
  'deleteCollection' : ActorMethod<[bigint], boolean>,
  'deleteDonor' : ActorMethod<[bigint], boolean>,
  'deleteInventoryUnit' : ActorMethod<[bigint], boolean>,
  'deletePatient' : ActorMethod<[bigint], boolean>,
  'getAllCollections' : ActorMethod<[], Array<Donation>>,
  'getAllDonors' : ActorMethod<[], Array<Donor>>,
  'getAllInventory' : ActorMethod<[], Array<InventoryUnit>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllRequests' : ActorMethod<[], Array<BloodRequest>>,
  'getBloodRequest' : ActorMethod<[bigint], [] | [BloodRequest]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollection' : ActorMethod<[bigint], [] | [Donation]>,
  'getDashboardSummary' : ActorMethod<[], BloodBankSummary>,
  'getDonor' : ActorMethod<[bigint], [] | [Donor]>,
  'getDonorsByBloodGroup' : ActorMethod<[BloodGroup], Array<Donor>>,
  'getInventoryByBloodGroup' : ActorMethod<[BloodGroup], Array<InventoryUnit>>,
  'getInventoryUnit' : ActorMethod<[bigint], [] | [InventoryUnit]>,
  'getPatient' : ActorMethod<[bigint], [] | [Patient]>,
  'getRequestsByStatus' : ActorMethod<[string], Array<BloodRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedBloodGroups' : ActorMethod<[], undefined>,
  'updateBloodRequest' : ActorMethod<[bigint, BloodRequest], boolean>,
  'updateCollection' : ActorMethod<[bigint, Donation], boolean>,
  'updateDonor' : ActorMethod<[bigint, Donor], boolean>,
  'updateInventoryUnit' : ActorMethod<[bigint, InventoryUnit], boolean>,
  'updatePatient' : ActorMethod<[bigint, Patient], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];