/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BloodGroup = IDL.Variant({
  'abNeg' : IDL.Null,
  'abPos' : IDL.Null,
  'aNeg' : IDL.Null,
  'aPos' : IDL.Null,
  'bNeg' : IDL.Null,
  'bPos' : IDL.Null,
  'oNeg' : IDL.Null,
  'oPos' : IDL.Null,
});
export const BloodRequest = IDL.Record({
  'status' : IDL.Text,
  'requestedTimestamp' : Time,
  'patientId' : IDL.Nat,
  'unitsNeeded' : IDL.Nat,
  'bloodGroup' : BloodGroup,
  'notes' : IDL.Text,
  'handledBy' : IDL.Text,
});
export const Donation = IDL.Record({
  'testStatus' : IDL.Text,
  'volumeMl' : IDL.Nat,
  'donorId' : IDL.Nat,
  'testedBy' : IDL.Text,
  'collectionTimestamp' : Time,
  'notes' : IDL.Text,
});
export const Donor = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'bloodGroup' : BloodGroup,
  'address' : IDL.Text,
  'gender' : IDL.Text,
  'registrationTimestamp' : Time,
  'lastDonationTimestamp' : Time,
  'phone' : IDL.Text,
});
export const InventoryUnit = IDL.Record({
  'status' : IDL.Text,
  'expiryTimestamp' : Time,
  'collectionId' : IDL.Nat,
  'collectedTimestamp' : Time,
  'bloodGroup' : BloodGroup,
  'units' : IDL.Nat,
});
export const Patient = IDL.Record({
  'age' : IDL.Nat,
  'hospital' : IDL.Text,
  'urgency' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'bloodGroup' : BloodGroup,
  'gender' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const BloodBankSummary = IDL.Record({
  'totalPatients' : IDL.Nat,
  'inventory' : IDL.Vec(IDL.Tuple(BloodGroup, IDL.Nat)),
  'pendingRequests' : IDL.Nat,
  'totalDonors' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBloodRequest' : IDL.Func([BloodRequest, IDL.Nat], [IDL.Nat], []),
  'createCollection' : IDL.Func([Donation, IDL.Nat], [IDL.Nat], []),
  'createDonor' : IDL.Func([Donor, IDL.Nat], [IDL.Nat], []),
  'createInventoryUnit' : IDL.Func([InventoryUnit, IDL.Nat], [IDL.Nat], []),
  'createPatient' : IDL.Func([Patient, IDL.Nat], [IDL.Nat], []),
  'deleteBloodRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCollection' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteDonor' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteInventoryUnit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePatient' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllCollections' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
  'getAllInventory' : IDL.Func([], [IDL.Vec(InventoryUnit)], ['query']),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
  'getBloodRequest' : IDL.Func([IDL.Nat], [IDL.Opt(BloodRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollection' : IDL.Func([IDL.Nat], [IDL.Opt(Donation)], ['query']),
  'getDashboardSummary' : IDL.Func([], [BloodBankSummary], ['query']),
  'getDonor' : IDL.Func([IDL.Nat], [IDL.Opt(Donor)], ['query']),
  'getDonorsByBloodGroup' : IDL.Func([BloodGroup], [IDL.Vec(Donor)], ['query']),
  'getInventoryByBloodGroup' : IDL.Func(
      [BloodGroup],
      [IDL.Vec(InventoryUnit)],
      ['query'],
    ),
  'getInventoryUnit' : IDL.Func([IDL.Nat], [IDL.Opt(InventoryUnit)], ['query']),
  'getPatient' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
  'getRequestsByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BloodRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedBloodGroups' : IDL.Func([], [], []),
  'updateBloodRequest' : IDL.Func([IDL.Nat, BloodRequest], [IDL.Bool], []),
  'updateCollection' : IDL.Func([IDL.Nat, Donation], [IDL.Bool], []),
  'updateDonor' : IDL.Func([IDL.Nat, Donor], [IDL.Bool], []),
  'updateInventoryUnit' : IDL.Func([IDL.Nat, InventoryUnit], [IDL.Bool], []),
  'updatePatient' : IDL.Func([IDL.Nat, Patient], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BloodGroup = IDL.Variant({
    'abNeg' : IDL.Null,
    'abPos' : IDL.Null,
    'aNeg' : IDL.Null,
    'aPos' : IDL.Null,
    'bNeg' : IDL.Null,
    'bPos' : IDL.Null,
    'oNeg' : IDL.Null,
    'oPos' : IDL.Null,
  });
  const BloodRequest = IDL.Record({
    'status' : IDL.Text,
    'requestedTimestamp' : Time,
    'patientId' : IDL.Nat,
    'unitsNeeded' : IDL.Nat,
    'bloodGroup' : BloodGroup,
    'notes' : IDL.Text,
    'handledBy' : IDL.Text,
  });
  const Donation = IDL.Record({
    'testStatus' : IDL.Text,
    'volumeMl' : IDL.Nat,
    'donorId' : IDL.Nat,
    'testedBy' : IDL.Text,
    'collectionTimestamp' : Time,
    'notes' : IDL.Text,
  });
  const Donor = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'bloodGroup' : BloodGroup,
    'address' : IDL.Text,
    'gender' : IDL.Text,
    'registrationTimestamp' : Time,
    'lastDonationTimestamp' : Time,
    'phone' : IDL.Text,
  });
  const InventoryUnit = IDL.Record({
    'status' : IDL.Text,
    'expiryTimestamp' : Time,
    'collectionId' : IDL.Nat,
    'collectedTimestamp' : Time,
    'bloodGroup' : BloodGroup,
    'units' : IDL.Nat,
  });
  const Patient = IDL.Record({
    'age' : IDL.Nat,
    'hospital' : IDL.Text,
    'urgency' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'bloodGroup' : BloodGroup,
    'gender' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const BloodBankSummary = IDL.Record({
    'totalPatients' : IDL.Nat,
    'inventory' : IDL.Vec(IDL.Tuple(BloodGroup, IDL.Nat)),
    'pendingRequests' : IDL.Nat,
    'totalDonors' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBloodRequest' : IDL.Func([BloodRequest, IDL.Nat], [IDL.Nat], []),
    'createCollection' : IDL.Func([Donation, IDL.Nat], [IDL.Nat], []),
    'createDonor' : IDL.Func([Donor, IDL.Nat], [IDL.Nat], []),
    'createInventoryUnit' : IDL.Func([InventoryUnit, IDL.Nat], [IDL.Nat], []),
    'createPatient' : IDL.Func([Patient, IDL.Nat], [IDL.Nat], []),
    'deleteBloodRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCollection' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteDonor' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteInventoryUnit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePatient' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllCollections' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAllDonors' : IDL.Func([], [IDL.Vec(Donor)], ['query']),
    'getAllInventory' : IDL.Func([], [IDL.Vec(InventoryUnit)], ['query']),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(BloodRequest)], ['query']),
    'getBloodRequest' : IDL.Func([IDL.Nat], [IDL.Opt(BloodRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollection' : IDL.Func([IDL.Nat], [IDL.Opt(Donation)], ['query']),
    'getDashboardSummary' : IDL.Func([], [BloodBankSummary], ['query']),
    'getDonor' : IDL.Func([IDL.Nat], [IDL.Opt(Donor)], ['query']),
    'getDonorsByBloodGroup' : IDL.Func(
        [BloodGroup],
        [IDL.Vec(Donor)],
        ['query'],
      ),
    'getInventoryByBloodGroup' : IDL.Func(
        [BloodGroup],
        [IDL.Vec(InventoryUnit)],
        ['query'],
      ),
    'getInventoryUnit' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(InventoryUnit)],
        ['query'],
      ),
    'getPatient' : IDL.Func([IDL.Nat], [IDL.Opt(Patient)], ['query']),
    'getRequestsByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BloodRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedBloodGroups' : IDL.Func([], [], []),
    'updateBloodRequest' : IDL.Func([IDL.Nat, BloodRequest], [IDL.Bool], []),
    'updateCollection' : IDL.Func([IDL.Nat, Donation], [IDL.Bool], []),
    'updateDonor' : IDL.Func([IDL.Nat, Donor], [IDL.Bool], []),
    'updateInventoryUnit' : IDL.Func([IDL.Nat, InventoryUnit], [IDL.Bool], []),
    'updatePatient' : IDL.Func([IDL.Nat, Patient], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };