/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BloodRequest {
    status: string;
    requestedTimestamp: Time;
    patientId: bigint;
    unitsNeeded: bigint;
    bloodGroup: BloodGroup;
    notes: string;
    handledBy: string;
}
export interface Donation {
    testStatus: string;
    volumeMl: bigint;
    donorId: bigint;
    testedBy: string;
    collectionTimestamp: Time;
    notes: string;
}
export type Time = bigint;
export interface InventoryUnit {
    status: string;
    expiryTimestamp: Time;
    collectionId: bigint;
    collectedTimestamp: Time;
    bloodGroup: BloodGroup;
    units: bigint;
}
export interface Donor {
    age: bigint;
    name: string;
    isActive: boolean;
    email: string;
    bloodGroup: BloodGroup;
    address: string;
    gender: string;
    registrationTimestamp: Time;
    lastDonationTimestamp: Time;
    phone: string;
}
export interface BloodBankSummary {
    totalPatients: bigint;
    inventory: Array<[BloodGroup, bigint]>;
    pendingRequests: bigint;
    totalDonors: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface Patient {
    age: bigint;
    hospital: string;
    urgency: string;
    name: string;
    isActive: boolean;
    bloodGroup: BloodGroup;
    gender: string;
    phone: string;
}
export enum BloodGroup {
    abNeg = "abNeg",
    abPos = "abPos",
    aNeg = "aNeg",
    aPos = "aPos",
    bNeg = "bNeg",
    bPos = "bPos",
    oNeg = "oNeg",
    oPos = "oPos"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface StoredUser {
    username: string;
    passwordHash: string;
    role: string;
    displayName: string;
}
export interface backendInterface {
    createBloodRequest(request: BloodRequest): Promise<bigint>;
    createCollection(collection: Donation): Promise<bigint>;
    createDonor(donor: Donor): Promise<bigint>;
    createInventoryUnit(unit: InventoryUnit): Promise<bigint>;
    createPatient(patient: Patient): Promise<bigint>;
    deleteBloodRequest(id: bigint): Promise<boolean>;
    deleteCollection(id: bigint): Promise<boolean>;
    deleteDonor(id: bigint): Promise<boolean>;
    deleteInventoryUnit(id: bigint): Promise<boolean>;
    deletePatient(id: bigint): Promise<boolean>;
    getAllCollections(): Promise<Array<[bigint, Donation]>>;
    getAllDonors(): Promise<Array<[bigint, Donor]>>;
    getAllInventory(): Promise<Array<[bigint, InventoryUnit]>>;
    getAllPatients(): Promise<Array<[bigint, Patient]>>;
    getAllRequests(): Promise<Array<[bigint, BloodRequest]>>;
    getBloodRequest(id: bigint): Promise<BloodRequest | null>;
    getCollection(id: bigint): Promise<Donation | null>;
    getDashboardSummary(): Promise<BloodBankSummary>;
    getDonor(id: bigint): Promise<Donor | null>;
    getDonorsByBloodGroup(bloodGroup: BloodGroup): Promise<Array<[bigint, Donor]>>;
    getInventoryByBloodGroup(bloodGroup: BloodGroup): Promise<Array<[bigint, InventoryUnit]>>;
    getInventoryUnit(id: bigint): Promise<InventoryUnit | null>;
    getPatient(id: bigint): Promise<Patient | null>;
    getRequestsByStatus(status: string): Promise<Array<[bigint, BloodRequest]>>;
    seedBloodGroups(): Promise<void>;
    updateBloodRequest(id: bigint, request: BloodRequest): Promise<boolean>;
    updateCollection(id: bigint, collection: Donation): Promise<boolean>;
    updateDonor(id: bigint, donor: Donor): Promise<boolean>;
    updateInventoryUnit(id: bigint, unit: InventoryUnit): Promise<boolean>;
    updatePatient(id: bigint, patient: Patient): Promise<boolean>;
    addUser(user: StoredUser): Promise<boolean>;
    getUser(username: string): Promise<StoredUser | null>;
    updateUserPassword(username: string, newPasswordHash: string): Promise<boolean>;
    getAllUsers(): Promise<Array<StoredUser>>;
}
import type { BloodBankSummary as _BloodBankSummary, BloodGroup as _BloodGroup, BloodRequest as _BloodRequest, Donation as _Donation, Donor as _Donor, InventoryUnit as _InventoryUnit, Patient as _Patient, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBloodRequest(arg0: BloodRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBloodRequest(to_candid_BloodRequest_n3(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBloodRequest(to_candid_BloodRequest_n3(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createCollection(arg0: Donation): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollection(arg0, arg1);
            return result;
        }
    }
    async createDonor(arg0: Donor): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDonor(to_candid_Donor_n7(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDonor(to_candid_Donor_n7(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createInventoryUnit(arg0: InventoryUnit): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryUnit(to_candid_InventoryUnit_n9(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryUnit(to_candid_InventoryUnit_n9(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createPatient(arg0: Patient): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(to_candid_Patient_n11(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(to_candid_Patient_n11(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async deleteBloodRequest(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBloodRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBloodRequest(arg0);
            return result;
        }
    }
    async deleteCollection(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCollection(arg0);
            return result;
        }
    }
    async deleteDonor(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDonor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDonor(arg0);
            return result;
        }
    }
    async deleteInventoryUnit(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryUnit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryUnit(arg0);
            return result;
        }
    }
    async deletePatient(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatient(arg0);
            return result;
        }
    }
    async getAllCollections(): Promise<Array<[bigint, Donation]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCollections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCollections();
            return result;
        }
    }
    async getAllDonors(): Promise<Array<[bigint, Donor]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonors();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonors();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInventory(): Promise<Array<[bigint, InventoryUnit]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventory();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventory();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPatients(): Promise<Array<[bigint, Patient]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRequests(): Promise<Array<[bigint, BloodRequest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBloodRequest(arg0: bigint): Promise<BloodRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBloodRequest(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBloodRequest(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollection(arg0: bigint): Promise<Donation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollection(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollection(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<BloodBankSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return from_candid_BloodBankSummary_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return from_candid_BloodBankSummary_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonor(arg0: bigint): Promise<Donor | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonor(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonor(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonorsByBloodGroup(arg0: BloodGroup): Promise<Array<[bigint, Donor]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonorsByBloodGroup(to_candid_BloodGroup_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonorsByBloodGroup(to_candid_BloodGroup_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryByBloodGroup(arg0: BloodGroup): Promise<Array<[bigint, InventoryUnit]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryByBloodGroup(to_candid_BloodGroup_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryByBloodGroup(to_candid_BloodGroup_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryUnit(arg0: bigint): Promise<InventoryUnit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryUnit(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryUnit(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatient(arg0: bigint): Promise<Patient | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequestsByStatus(arg0: string): Promise<Array<[bigint, BloodRequest]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequestsByStatus(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequestsByStatus(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedBloodGroups(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedBloodGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedBloodGroups();
            return result;
        }
    }
    async updateBloodRequest(arg0: bigint, arg1: BloodRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBloodRequest(arg0, to_candid_BloodRequest_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBloodRequest(arg0, to_candid_BloodRequest_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCollection(arg0: bigint, arg1: Donation): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCollection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCollection(arg0, arg1);
            return result;
        }
    }
    async updateDonor(arg0: bigint, arg1: Donor): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDonor(arg0, to_candid_Donor_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDonor(arg0, to_candid_Donor_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateInventoryUnit(arg0: bigint, arg1: InventoryUnit): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryUnit(arg0, to_candid_InventoryUnit_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryUnit(arg0, to_candid_InventoryUnit_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePatient(arg0: bigint, arg1: Patient): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, to_candid_Patient_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, to_candid_Patient_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addUser(user: any): Promise<boolean> {
        try { return await (this.actor as any).addUser(user); } catch(e) { return false; }
    }
    async getUser(username: string): Promise<any> {
        try { const r = await (this.actor as any).getUser(username); return r && r.length > 0 ? r[0] : null; } catch(e) { return null; }
    }
    async updateUserPassword(username: string, newHash: string): Promise<boolean> {
        try { return await (this.actor as any).updateUserPassword(username, newHash); } catch(e) { return false; }
    }
    async getAllUsers(): Promise<any[]> {
        try { return await (this.actor as any).getAllUsers(); } catch(e) { return []; }
    }
}
function from_candid_BloodBankSummary_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodBankSummary): BloodBankSummary {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_BloodGroup_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodGroup): BloodGroup {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_BloodRequest_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodRequest): BloodRequest {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Donor_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Donor): Donor {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryUnit_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryUnit): InventoryUnit {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BloodRequest]): BloodRequest | null {
    return value.length === 0 ? null : from_candid_BloodRequest_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donation]): Donation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Donor]): Donor | null {
    return value.length === 0 ? null : from_candid_Donor_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryUnit]): InventoryUnit | null {
    return value.length === 0 ? null : from_candid_InventoryUnit_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Patient]): Patient | null {
    return value.length === 0 ? null : from_candid_Patient_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    isActive: boolean;
    email: string;
    bloodGroup: _BloodGroup;
    address: string;
    gender: string;
    registrationTimestamp: _Time;
    lastDonationTimestamp: _Time;
    phone: string;
}): {
    age: bigint;
    name: string;
    isActive: boolean;
    email: string;
    bloodGroup: BloodGroup;
    address: string;
    gender: string;
    registrationTimestamp: Time;
    lastDonationTimestamp: Time;
    phone: string;
} {
    return {
        age: value.age,
        name: value.name,
        isActive: value.isActive,
        email: value.email,
        bloodGroup: from_candid_BloodGroup_n16(_uploadFile, _downloadFile, value.bloodGroup),
        address: value.address,
        gender: value.gender,
        registrationTimestamp: value.registrationTimestamp,
        lastDonationTimestamp: value.lastDonationTimestamp,
        phone: value.phone
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    expiryTimestamp: _Time;
    collectionId: bigint;
    collectedTimestamp: _Time;
    bloodGroup: _BloodGroup;
    units: bigint;
}): {
    status: string;
    expiryTimestamp: Time;
    collectionId: bigint;
    collectedTimestamp: Time;
    bloodGroup: BloodGroup;
    units: bigint;
} {
    return {
        status: value.status,
        expiryTimestamp: value.expiryTimestamp,
        collectionId: value.collectionId,
        collectedTimestamp: value.collectedTimestamp,
        bloodGroup: from_candid_BloodGroup_n16(_uploadFile, _downloadFile, value.bloodGroup),
        units: value.units
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    hospital: string;
    urgency: string;
    name: string;
    isActive: boolean;
    bloodGroup: _BloodGroup;
    gender: string;
    phone: string;
}): {
    age: bigint;
    hospital: string;
    urgency: string;
    name: string;
    isActive: boolean;
    bloodGroup: BloodGroup;
    gender: string;
    phone: string;
} {
    return {
        age: value.age,
        hospital: value.hospital,
        urgency: value.urgency,
        name: value.name,
        isActive: value.isActive,
        bloodGroup: from_candid_BloodGroup_n16(_uploadFile, _downloadFile, value.bloodGroup),
        gender: value.gender,
        phone: value.phone
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    requestedTimestamp: _Time;
    patientId: bigint;
    unitsNeeded: bigint;
    bloodGroup: _BloodGroup;
    notes: string;
    handledBy: string;
}): {
    status: string;
    requestedTimestamp: Time;
    patientId: bigint;
    unitsNeeded: bigint;
    bloodGroup: BloodGroup;
    notes: string;
    handledBy: string;
} {
    return {
        status: value.status,
        requestedTimestamp: value.requestedTimestamp,
        patientId: value.patientId,
        unitsNeeded: value.unitsNeeded,
        bloodGroup: from_candid_BloodGroup_n16(_uploadFile, _downloadFile, value.bloodGroup),
        notes: value.notes,
        handledBy: value.handledBy
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalPatients: bigint;
    inventory: Array<[_BloodGroup, bigint]>;
    pendingRequests: bigint;
    totalDonors: bigint;
}): {
    totalPatients: bigint;
    inventory: Array<[BloodGroup, bigint]>;
    pendingRequests: bigint;
    totalDonors: bigint;
} {
    return {
        totalPatients: value.totalPatients,
        inventory: from_candid_vec_n34(_uploadFile, _downloadFile, value.inventory),
        pendingRequests: value.pendingRequests,
        totalDonors: value.totalDonors
    };
}
function from_candid_tuple_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_BloodGroup, bigint]): [BloodGroup, bigint] {
    return [
        from_candid_BloodGroup_n16(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    abNeg: null;
} | {
    abPos: null;
} | {
    aNeg: null;
} | {
    aPos: null;
} | {
    bNeg: null;
} | {
    bPos: null;
} | {
    oNeg: null;
} | {
    oPos: null;
}): BloodGroup {
    return "abNeg" in value ? BloodGroup.abNeg : "abPos" in value ? BloodGroup.abPos : "aNeg" in value ? BloodGroup.aNeg : "aPos" in value ? BloodGroup.aPos : "bNeg" in value ? BloodGroup.bNeg : "bPos" in value ? BloodGroup.bPos : "oNeg" in value ? BloodGroup.oNeg : "oPos" in value ? BloodGroup.oPos : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Donor>): Array<Donor> {
    return value.map((x)=>from_candid_Donor_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryUnit>): Array<InventoryUnit> {
    return value.map((x)=>from_candid_InventoryUnit_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BloodRequest>): Array<BloodRequest> {
    return value.map((x)=>from_candid_BloodRequest_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_BloodGroup, bigint]>): Array<[BloodGroup, bigint]> {
    return value.map((x)=>from_candid_tuple_n35(_uploadFile, _downloadFile, x));
}
function to_candid_BloodGroup_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): _BloodGroup {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_BloodRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodRequest): _BloodRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Donor_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Donor): _Donor {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryUnit_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryUnit): _InventoryUnit {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Patient_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Patient): _Patient {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    expiryTimestamp: Time;
    collectionId: bigint;
    collectedTimestamp: Time;
    bloodGroup: BloodGroup;
    units: bigint;
}): {
    status: string;
    expiryTimestamp: _Time;
    collectionId: bigint;
    collectedTimestamp: _Time;
    bloodGroup: _BloodGroup;
    units: bigint;
} {
    return {
        status: value.status,
        expiryTimestamp: value.expiryTimestamp,
        collectionId: value.collectionId,
        collectedTimestamp: value.collectedTimestamp,
        bloodGroup: to_candid_BloodGroup_n5(_uploadFile, _downloadFile, value.bloodGroup),
        units: value.units
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    hospital: string;
    urgency: string;
    name: string;
    isActive: boolean;
    bloodGroup: BloodGroup;
    gender: string;
    phone: string;
}): {
    age: bigint;
    hospital: string;
    urgency: string;
    name: string;
    isActive: boolean;
    bloodGroup: _BloodGroup;
    gender: string;
    phone: string;
} {
    return {
        age: value.age,
        hospital: value.hospital,
        urgency: value.urgency,
        name: value.name,
        isActive: value.isActive,
        bloodGroup: to_candid_BloodGroup_n5(_uploadFile, _downloadFile, value.bloodGroup),
        gender: value.gender,
        phone: value.phone
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    requestedTimestamp: Time;
    patientId: bigint;
    unitsNeeded: bigint;
    bloodGroup: BloodGroup;
    notes: string;
    handledBy: string;
}): {
    status: string;
    requestedTimestamp: _Time;
    patientId: bigint;
    unitsNeeded: bigint;
    bloodGroup: _BloodGroup;
    notes: string;
    handledBy: string;
} {
    return {
        status: value.status,
        requestedTimestamp: value.requestedTimestamp,
        patientId: value.patientId,
        unitsNeeded: value.unitsNeeded,
        bloodGroup: to_candid_BloodGroup_n5(_uploadFile, _downloadFile, value.bloodGroup),
        notes: value.notes,
        handledBy: value.handledBy
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    isActive: boolean;
    email: string;
    bloodGroup: BloodGroup;
    address: string;
    gender: string;
    registrationTimestamp: Time;
    lastDonationTimestamp: Time;
    phone: string;
}): {
    age: bigint;
    name: string;
    isActive: boolean;
    email: string;
    bloodGroup: _BloodGroup;
    address: string;
    gender: string;
    registrationTimestamp: _Time;
    lastDonationTimestamp: _Time;
    phone: string;
} {
    return {
        age: value.age,
        name: value.name,
        isActive: value.isActive,
        email: value.email,
        bloodGroup: to_candid_BloodGroup_n5(_uploadFile, _downloadFile, value.bloodGroup),
        address: value.address,
        gender: value.gender,
        registrationTimestamp: value.registrationTimestamp,
        lastDonationTimestamp: value.lastDonationTimestamp,
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): {
    abNeg: null;
} | {
    abPos: null;
} | {
    aNeg: null;
} | {
    aPos: null;
} | {
    bNeg: null;
} | {
    bPos: null;
} | {
    oNeg: null;
} | {
    oPos: null;
} {
    return value == BloodGroup.abNeg ? {
        abNeg: null
    } : value == BloodGroup.abPos ? {
        abPos: null
    } : value == BloodGroup.aNeg ? {
        aNeg: null
    } : value == BloodGroup.aPos ? {
        aPos: null
    } : value == BloodGroup.bNeg ? {
        bNeg: null
    } : value == BloodGroup.bPos ? {
        bPos: null
    } : value == BloodGroup.oNeg ? {
        oNeg: null
    } : value == BloodGroup.oPos ? {
        oPos: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
